"""
Add new columns for remote jobs

Revision ID: 6367db8d4199
Revises:
Create Date: 2025-02-26 11:59:03.281528

"""

from __future__ import annotations

import uuid
from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Column
from sqlalchemy.dialects.sqlite import INTEGER
from sqlalchemy.dialects.sqlite import JSON
from sqlalchemy.dialects.sqlite import TEXT
from sqlalchemy.dialects.sqlite import TIMESTAMP
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = "6367db8d4199"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # In some cases we might not even have a base table for butler jobs, create them
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if "butler_job" not in tables:
        op.create_table(
            "butler_job",
            Column(
                "job_id",
                TEXT,
                primary_key=True,
                default=lambda _: str(uuid.uuid4()),
            ),
            Column("job_type", TEXT, nullable=False),
            Column("context", JSON, nullable=False),
            Column("status", TEXT, nullable=False, default="PENDING"),
            Column("failure_reason", TEXT),
            Column("retry_attempts", INTEGER, nullable=False, default=0),
            Column(
                "create_time",
                TIMESTAMP(timezone=True),
                nullable=False,
                server_default=sa.sql.func.now(),
            ),
            Column(
                "update_time",
                TIMESTAMP(timezone=True),
                server_default=sa.sql.func.now(),
                onupdate=sa.sql.func.current_timestamp(),
            ),
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "butler_job",
        sa.Column(
            "source", sa.TEXT(), nullable=False, server_default="unknown"
        ),
    )
    op.add_column(
        "butler_job", sa.Column("concurrency_locks", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "butler_job", sa.Column("created_by_version", sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("butler_job", "created_by_version")
    op.drop_column("butler_job", "concurrency_locks")
    op.drop_column("butler_job", "source")
    # ### end Alembic commands ###
