"""
create cancellation request

Revision ID: 0a0a2611fcbb
Revises: 6367db8d4199
Create Date: 2025-11-24 17:48:20.723917

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0a0a2611fcbb"
down_revision: Union[str, None] = "6367db8d4199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "butler_job",
        sa.Column(
            "cancel_requested", sa.BOOLEAN(), nullable=False, default=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("butler_job", "cancel_requested")
    # ### end Alembic commands ###
